### ISSUE TITLE
Option to continue with the foreach loop when an iteration fails

### ISSUE THREAD

**Issue by daigotanaka** [anelendata/handoff#119]
We will introduce `kill_downstream_on_fail` and `kill_loop_on_fail` that can be set under "tasks" section or at each task:
By default, both are set to True, meaning that one failure will immediately kill the entire job.

```
# Default for kill_downstream_on_fail is True. By setting False, it will continue to verify_result task even if generate_files task fails.
kill_downstream_on_fail: False

tasks:                                                                           
- name: generate_files
  # Default is true for kill_loop_on_fail: It will exit the loop on one fail.
  kill_loop_on_fail: False
  # task specific setting: "False" here will run loop_task_2 even if loop_task_1 fails
  kill_downstream_on_fail: False

  pipeline:                                                                      
  - command: cat                                                                 
    args: files/in.txt                                                           
  - foreach:                                                                     
    - name: loop_task_1                                                        
      pipeline:                                                                  
      - command: python3 files/run.py {{ _line }}                                
      - command: "cat >> ./artifacts/list_double.txt"                            
    - name: loop_task_2                                                     
      commands:                                                                  
      - command: "echo {{ _line }} >> ./artifacts/list.txt"

- name: verify_result
  pipeline:
  - command: cat list.txt
```
