### ISSUE TITLE
Custom Dockerfile

### ISSUE THREAD

**Issue by daigotanaka** [anelendata/handoff#39]
We may need to deploy Docker image with special installations (e.g. JDBC driver). This is beyond the capability of `workspace install` command.

**Comment by daigotanaka** [comment]
At least for the users familiar with Docker, providing the interface for specifying their own Dockerfile is a minimally viable feature to solve the problem.

**Comment by daigotanaka** [comment]
Also, allow user to provide supporting files:

```
container:
    engine: docker
    config:
      docker_file: ./Dockerfile
      files_dir: ./my_files
```

So, they refer it from Dockerfile like:

```
COPY ./my_files/hello.txt /app/ 
```
