### ISSUE TITLE
"environment variable is not defined" for HO_RESOURCE_GROUP, TASK, BUCKET...

### ISSUE THREAD

**Issue by daigotanaka** [anelendata/handoff#41]
When running `handoff cloud create_bucket`, you may get:
```
CRITICAL - 2020-09-04 11:40:14,085 - handoff.config - HO_RESOURCE_GROUP environment variable is not defined. Valid pattern: ^[a-zA-Z][a-zA-Z0-9-]*$
CRITICAL - 2020-09-04 11:40:14,085 - handoff.config - HO_TASK environment variable is not defined. Valid pattern: ^[a-zA-Z][a-zA-Z0-9-]*$
CRITICAL - 2020-09-04 11:40:14,085 - handoff.config - HO_BUCKET environment variable is not defined. Valid pattern: ^[a-z0-9][a-z0-9.-]*$
CRITICAL - 2020-09-04 11:40:14,086 - handoff.config - HO_DOCKER_IMAGE environment variable is not defined. Valid pattern: ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
```

It's because project.yml needs an entries like:
```
deploy:
  provider: "aws"
  platform: "fargate"
  envs:
    resource_group: "handoff-test"
    docker_image: "singer_exchange_rates_to_csv"
    task: "test-03-exchange-rates"
```

The errors message should clearly instruct on where to add the missing variables.
