### ISSUE TITLE
Installing non-Python programs

### ISSUE THREAD

**Issue by daigotanaka** [anelendata/handoff#42]
handoff always tries to switches to a virtual env before running installation command. Think of this example:

```
commands:
  - command: teleport
    args: extract-load-api -from coindesk_bitcoin_price_index -to warehouse
    installs:
      - "curl -fsSL https://github.com/hundredwatt/teleport/releases/download/v0.0.1-alpha.6/teleport_0.0.1-alpha.6.linux-x86_64.tar.gz | tar -xzv teleport_0.0.1-alpha.6.linux-x86_64/teleport"
      - "mv teleport_0.0.1-alpha.6.linux-x86_64/teleport teleport"
      - "mv teleport /usr/local/bin/teleport"
```

The program does not require a Python environment but handoff installation fails because `venv` entry is missing from teleport command in this project.yml.

Current work around is to add a `venv` entry whether or not this is a Python program:
```
commands:
  - command: teleport
    args: extract-load-api -from coindesk_bitcoin_price_index -to warehouse
    venv: "proc_01"
    installs:
      - "curl -fsSL https://github.com/hundredwatt/teleport/releases/download/v0.0.1-alpha.6/teleport_0.0.1-alpha.6.linux-x86_64.tar.gz | tar -xzv teleport_0.0.1-alpha.6.linux-x86_64/teleport"
      - "mv teleport_0.0.1-alpha.6.linux-x86_64/teleport teleport"
      - "mv teleport /usr/local/bin/teleport"
```
