### ISSUE TITLE
Optional template for required secrets in project.yml

### ISSUE THREAD

**Issue by daigotanaka** [anelendata/handoff#97]
This is for the system to check if all the required secrets are defined before executing the task. This section does not accept the values:
```
secrets:
- key: <key_name_1>
  level: task
  description: Some help text
- key: <key_name_2>
  level: resource group
...
```
